version: '3'

services:
  eosstracker:
    image: thekoola/eosstracker:brickv2.1
    devices:
      - /dev/bus/usb
    container_name: eosstracker
    restart: unless-stopped
    command: /run.sh
    environment:
      - TZ=America/Denver
    volumes:
      - /opt/eosstracker/config/eosstracker:/eosstracker
    ports:
      - "8422:443"
      - "9988:14501"
