version: '3'

services:
  eosstracker:
    image: thekoola/eosstracker:brickv2.1
    devices:
      - /dev/bus/usb
      - /dev/ttyUSB0
    container_name: eosstracker
    restart: unless-stopped
    network_mode: host
    command: /run.sh
    environment:
      - TZ=America/Denver
      - GPS_DEVICE=/dev/ttyUSB0
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./data:/eosstracker
