services:
  eosstracker:
    image: thekoola/eosstracker:brickv2.1
    devices:
      - /dev/bus/usb
      - /dev/ttyACM0
    container_name: eosstracker
    restart: unless-stopped
    network_mode: host
    command: /run.sh
    environment:
      - TZ=America/Denver
      - GPS_DEVICE=/dev/ttyACM0
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./data:/eosstracker
    ports:
      - 80:80
      - 443:443
      - 14501:14501