#!/bin/bash
#
# Added by JTS on 2019-09-07
#

DESTFILE=/etc/rc.local
BASEDIR=/opt/aprsc
DIRNAME=aprsc
NAME=fix-aprsc

ME=$(whoami)
if [ ${ME} != "root" ]; then
        echo "$NAME: not running as root... exiting"
        exit 1
fi

# Edits to rc.local
if [ -f $DESTFILE ]; then
        echo "$NAME: Updating $DESTFILE..."

echo "#!/bin/bash
#
# Added by JTS and JED on 2019-01-28
# Updated by JTS on 2019-09-07
# Autogenerated by EOSS to set up aprsc >= 2.1.5 chroot environment
#

BASEDIR=/opt/aprsc
DIRNAME=aprsc

# Fixing network on boot
nmcli con up Hotspot

# Grab the hotspot SSID and put that into the WWW home directory for display on the main web page
if [ -f /etc/NetworkManager/system-connections/Hotspot ]; then
    awk -F\"=\" '/^ssid=/ {print \$2;}' /etc/NetworkManager/system-connections/Hotspot > /eosstracker/www/nodeid.txt
    chmod 444 /eosstracker/www/nodeid.txt
else
    rm -f /eosstracker/www/nodeid.txt
fi" > $DESTFILE

echo "
# Check and add necessary directories and mount points for aprsc >= 2.1.5
if [ ! -d \$BASEDIR/etc ]; then
        /bin/mkdir -p -m 755 \$BASEDIR/etc
fi
if [ ! -d \$BASEDIR/dev ]; then
        /bin/mkdir -p -m 755 \$BASEDIR/dev
fi
if [ ! -d \$BASEDIR/lib ]; then
        /bin/mkdir -p -m 755 \$BASEDIR/lib
fi
if [ ! -d \$BASEDIR/lib64 ]; then
        /bin/mkdir -p -m 755 \$BASEDIR/lib64
fi
if [ ! -d \$BASEDIR/usr/lib ]; then
        /bin/mkdir -p -m 755 \$BASEDIR/usr/lib
fi
if [ ! -d \$BASEDIR/usr/lib64 ]; then
        /bin/mkdir -p -m 755 \$BASEDIR/usr/lib64
fi" >> $DESTFILE

echo "
# Copy files and special devices for aprsc >= 2.1.5 chroot environment
if [ ! -e \$BASEDIR/etc/gai.conf ]; then
        /bin/cp -p /etc/resolv.conf /etc/nsswitch.conf /etc/hosts /etc/gai.conf \$BASEDIR/etc/
fi
if [ ! -e \$BASEDIR/dev/random ]; then
        /bin/cp -pa /dev/urandom /dev/random /dev/null /dev/zero \$BASEDIR/dev/
fi" >> $DESTFILE

echo "
# Mount libraries read-only for aprsc >= 2.1.5 chroot environment
grep -q \"\$DIRNAME/lib \" /proc/mounts || \
( mount --bind /lib \$BASEDIR/lib \
&& mount -o remount,ro,bind \$BASEDIR/lib )

if [ -e /lib64 ]; then
     grep -q \"\$DIRNAME/lib64 \" /proc/mounts || \
( mount --bind /lib64 \$BASEDIR/lib64 \
&& mount -o remount,ro,bind \$BASEDIR/lib64 )
fi

grep -q \"\$DIRNAME/usr/lib \" /proc/mounts || \
( mount --bind /usr/lib \$BASEDIR/usr/lib \
&& mount -o remount,ro,bind \$BASEDIR/usr/lib )

if [ -e /usr/lib64 ]; then
     grep -q \"\$DIRNAME/usr/lib64 \" /proc/mounts || \
( mount --bind /usr/lib64 \$BASEDIR/usr/lib64 \
&& mount -o remount,ro,bind \$BASEDIR/usr/lib64 )
fi" >> $DESTFILE

echo "
exit 0" >> $DESTFILE

chmod 755 $DESTFILE

fi  # Edits to rc.local

# Check and add necessary directories and mount points for aprsc >= 2.1.5
echo "$NAME: Checking for and adding aprsc mount points..."
if [ ! -d $BASEDIR/etc ]; then
        /bin/mkdir -p -m 755 $BASEDIR/etc
fi
if [ ! -d $BASEDIR/dev ]; then
        /bin/mkdir -p -m 755 $BASEDIR/dev
fi
if [ ! -d $BASEDIR/lib ]; then
        /bin/mkdir -p -m 755 $BASEDIR/lib
fi
if [ ! -d $BASEDIR/lib64 ]; then
        /bin/mkdir -p -m 755 $BASEDIR/lib64
fi
if [ ! -d $BASEDIR/usr/lib ]; then
        /bin/mkdir -p -m 755 $BASEDIR/usr/lib
fi
if [ ! -d $BASEDIR/usr/lib64 ]; then
        /bin/mkdir -p -m 755 $BASEDIR/usr/lib64
fi

# Copy files and special devices for aprsc >= 2.1.5 chroot environment
echo "$NAME: Copying necessary files and special devices for aprsc..."
if [ ! -e $BASEDIR/etc/gai.conf ]; then
        /bin/cp -p /etc/resolv.conf /etc/nsswitch.conf /etc/hosts /etc/gai.conf $BASEDIR/etc/
fi
if [ ! -e $BASEDIR/dev/random ]; then
        /bin/cp -pa /dev/urandom /dev/random /dev/null /dev/zero $BASEDIR/dev/
fi

# Mount libraries read-only for aprsc >= 2.1.5 chroot environment
echo "$NAME: Mounting libraries read-only for aprsc..."
grep -q "$DIRNAME/lib " /proc/mounts || \
     ( mount --bind /lib $BASEDIR/lib \
     && mount -o remount,ro,bind $BASEDIR/lib )

if [ -e /lib64 ]; then
     grep -q "$DIRNAME/lib64 " /proc/mounts || \
     ( mount --bind /lib64 $BASEDIR/lib64 \
     && mount -o remount,ro,bind $BASEDIR/lib64 )
fi

grep -q "$DIRNAME/usr/lib " /proc/mounts || \
     ( mount --bind /usr/lib $BASEDIR/usr/lib \
     && mount -o remount,ro,bind $BASEDIR/usr/lib )

if [ -e /usr/lib64 ]; then
     grep -q "$DIRNAME/usr/lib64 " /proc/mounts || \
     ( mount --bind /usr/lib64 $BASEDIR/usr/lib64 \
     && mount -o remount,ro,bind $BASEDIR/usr/lib64 )
fi

exit 0
